#!/usr/bin/env python3
"""Writes one Nano Banana prompt per store asset.

Every prompt carries the same non-negotiable instruction — the supplied
screenshot is the source of truth and the interface inside it may not be
redrawn, reinterpreted or "improved" — because that is the one way an image
model can ruin a store listing. The rendered text (headline, supporting line)
is *not* generated by the model: it is drawn deterministically by
`compose_assets.py` with the app's own font, so no model ever re-writes Arabic.

    python3 tool/store_capture/generate_prompts.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, os.environ.get("DH_OUT", "DHIMMAH_STORE_ASSETS"))
STORY = os.path.join(ROOT, "tool", "store_capture", "store_story.json")

# The canvas and the margin are the compositor's, not a second copy of the same
# numbers: a prompt that describes a different page than the one that exists
# would be worse than no prompt.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from compose_assets import (  # noqa: E402  (after the path insert, deliberately)
    FEATURE_H,
    FEATURE_W,
    MARGIN,
    PHONE_H,
    PHONE_W,
)

PRESERVE = """The supplied screenshot is the source of truth.

Preserve the exact application UI. Every pixel of the interface must remain
identical to the source:

- numbers, amounts and currency symbols
- names and every word of text
- dates
- buttons and their labels
- icons
- navigation bars and tabs
- typography, weights and line breaks
- the state each screen is in (what is selected, what is scrolled, what is open)

Do not redraw, reinterpret, replace, invent, or modify the app interface."""

STYLE = """A calm, typography-led composition on warm paper (#F7F5F2). Restrained
colour, generous whitespace, precise alignment, one subtle shadow. The app's UI
is the subject; the marketing layer is quiet around it. No gradients, no neon,
no glassmorphism, no 3D, no floating device mockups, no blobs, no emoji, no
badges, no invented charts."""

# What each currency is called, so a prompt never describes the money loosely.
CURRENCY_NAMES = {
    "YER": "Yemeni riyal (YER, ﷼)",
    "USD": "US dollar (USD, $)",
    "SAR": "Saudi riyal (SAR, ﷼)",
    "AED": "UAE dirham (AED, د.إ)",
    "EUR": "euro (EUR, €)",
    "GBP": "pound sterling (GBP, £)",
}


def prompt_doc(*, number: str, platform: str, device: str, language: str,
               currency: str, canvas: str, source: str, objective: str,
               composition: str, headline: str, support: str, safe_area: str,
               output: str, alt: str) -> str:
    return f"""# {number} — {source}

IMAGE NUMBER
{number}

PLATFORM
{platform}

DEVICE
{device}

LANGUAGE
{language}

CURRENCY
{currency}

CANVAS
{canvas}

SOURCE SCREENSHOT
{source}

OBJECTIVE
{objective}

COMPOSITION
{composition}

HEADLINE
{headline}

SUPPORTING COPY
{support}

SAFE AREA
{safe_area}

MUST PRESERVE
{PRESERVE}

DO NOT CHANGE
Anything inside the screenshot. Do not touch the app's interface, text, numbers,
icons, buttons, navigation or layout. Do not add UI elements, badges, ratings,
awards, store logos, download prompts or device frames that were not there.

STYLE
{STYLE}

ACCESSIBILITY
The headline must keep at least a 4.5:1 contrast against its background. No text
over the app UI. Alt text, for the store listing field:
{alt}

OUTPUT REQUIREMENTS
{output}
"""


def write_text(path: str, text: str) -> None:
    """Writes a prompt into the package, and nowhere else.

    Every path here is built from this repository's own story file and a fixed
    language list, so it cannot escape on its own; the containment check is here
    so that it never can, whatever a future edit to the copy does.
    """
    target = os.path.realpath(path)
    package = os.path.realpath(OUT) + os.sep
    if not target.startswith(package):
        raise SystemExit(f"refusing to write outside the package: {path}")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    Path(target).write_text(text, encoding="utf-8")
    print(f"wrote {os.path.relpath(target, ROOT)}")


def main() -> None:
    with open(STORY, encoding="utf-8") as fh:
        story = json.load(fh)
    declared = story.get("currency", {})

    for lang in ("ar", "en"):
        target = os.path.join(OUT, "05_NANO_BANANA_PROMPTS", "GOOGLE_PLAY")
        os.makedirs(target, exist_ok=True)
        code = declared.get(lang, "USD")
        currency = (f"{CURRENCY_NAMES.get(code, code)}. Every amount in the "
                    "screenshot is already drawn in it: do not convert, restate "
                    "or reformat a single figure.")
        for index, screen in enumerate(story["screens"], start=1):
            slug = screen["source"][3:]
            name = f"{index:02d}_{slug}_{lang}_google_nano_banana_prompt.md"
            doc = prompt_doc(
                number=f"{index:02d} of 8 — Google Play phone, {lang.upper()}",
                platform="Google Play",
                device="Android phone (portrait only)",
                language="Arabic (RTL)" if lang == "ar" else "English (LTR)",
                currency=currency,
                canvas=f"{PHONE_W} × {PHONE_H} (9:16), PNG, no alpha",
                source=f"04_SOURCE_SCREENSHOTS/ANDROID/{lang.upper()}/{screen['source']}_{lang}.png",
                objective=screen[f"objective_{lang}"],
                composition=screen.get(
                    "composition",
                    "Brand row (mark + wordmark) at the top on the reading side; "
                    "headline beneath it; one supporting line; the app screenshot "
                    "centred below in a rounded frame with a soft shadow, scaled to "
                    "fit whole — never cropped.",
                ),
                headline=screen[f"headline_{lang}"] + "\n(Already rendered deterministically — reuse, do not re-typeset.)",
                support=screen[f"support_{lang}"] + "\n(Already rendered deterministically — reuse, do not re-typeset.)",
                safe_area=f"Keep {MARGIN} px clear on every edge. Nothing important "
                          "within the outer 60 px.",
                output=f"PNG, {PHONE_W} × {PHONE_H}, no transparency, sRGB, under 8 MB.",
                alt=screen[f"alt_{lang}"],
            )
            write_text(os.path.join(target, name), doc)

        # The dark dashboard, if the compositor produced one: an asset ships with
        # a prompt, or it does not ship.
        dark_extra = story.get("dark_extra")
        dark_asset = os.path.join(OUT, "01_GOOGLE_PLAY", f"PHONE_{lang.upper()}",
                                  "ALTERNATES",
                                  f"01_dashboard_dark_{lang}_google_{PHONE_W}x{PHONE_H}.png")
        if dark_extra and os.path.exists(dark_asset):
            name = f"01_dashboard_dark_{lang}_google_nano_banana_prompt.md"
            doc = prompt_doc(
                number=f"Dark alternate — Google Play phone, {lang.upper()}",
                platform="Google Play",
                device="Android phone (portrait only)",
                language="Arabic (RTL)" if lang == "ar" else "English (LTR)",
                currency=currency,
                canvas=f"{PHONE_W} × {PHONE_H} (9:16), PNG, no alpha",
                source=f"04_SOURCE_SCREENSHOTS/ANDROID/{lang.upper()}/01_dashboard_dark_{lang}.png",
                objective=dark_extra[f"objective_{lang}"],
                composition="The same page as slide 01 on the dark palette "
                            "(#131211 page, #F2EFEA ink), so it can replace slide 01 "
                            "if the whole listing is ever made dark.",
                headline=dark_extra[f"headline_{lang}"] + "\n(Already rendered deterministically — reuse, do not re-typeset.)",
                support=dark_extra[f"support_{lang}"] + "\n(Already rendered deterministically — reuse, do not re-typeset.)",
                safe_area=f"Keep {MARGIN} px clear on every edge. Nothing important "
                          "within the outer 60 px.",
                output=f"PNG, {PHONE_W} × {PHONE_H}, no transparency, sRGB, under 8 MB.",
                alt=dark_extra[f"alt_{lang}"],
            )
            write_text(os.path.join(target, name), doc)

        # The feature graphic is composed, not captured; its prompt says so.
        name = f"feature_graphic_{lang}_google_nano_banana_prompt.md"
        doc = prompt_doc(
            number="Feature graphic — Google Play",
            platform="Google Play",
            device="All (shown at the top of the listing)",
            language="Arabic (RTL)" if lang == "ar" else "English (LTR)",
            currency="No amount appears in this asset.",
            canvas=f"{FEATURE_W} × {FEATURE_H}, PNG, no alpha",
            source="assets/icon/icon_mark.png (the shipped brand mark)",
            objective="A banner that is recognisably Dhimmah in one glance.",
            composition="The mark and the wordmark, centred as one unit "
                        "(mark leading on the reading side), on warm paper.",
            headline="ذِمّة" if lang == "ar" else "Dhimmah",
            support="اعرف ما لك وما عليك" if lang == "ar"
                    else "Know what you owe. Know what you're owed.",
            safe_area="Keep 96 px clear on the left and right; the centre must "
                      "read at thumbnail size.",
            output=f"PNG, {FEATURE_W} × {FEATURE_H}, no transparency, sRGB, under 15 MB.",
            alt="The Dhimmah mark and wordmark on a warm paper background."
            if lang == "en" else "شعار ذِمّة واسمها على خلفية ورقية دافئة.",
        )
        write_text(os.path.join(target, name), doc)


if __name__ == "__main__":
    main()
